Import services from https://github.com/ambanum/OpenTermsArchive
OpenTermsArchive/services-all pull request #98
Opened 2021-11-25 14:39 UTC by Ndpnt

2021-11-30 06:06 UTC, martinratinaud approved these changes
Tested on local and it works great. Congrats

2021-11-30 15:21 UTC, MattiSG requested changes

2021-11-30 15:21 UTC, MattiSG commented on package.json
> +    "mocha": "^9.1.3",
These should be dependencies of OTA, not of the services repository.

2021-11-30 15:21 UTC, MattiSG commented on .github/workflows/test.yml
> +name: Validate services
Only changed service should be validated, as they were on OTA 🙂

2021-11-30 15:21 UTC, MattiSG commented on README.md
> +This repository is to be considered as a database of services declarations used by [Open Terms Archive](https://github.com/ambanum/OpenTermsArchive).
```suggestion
The database of services tracked on [Open Terms Archive](https://opentermsarchive.org).
```

2021-11-30 15:21 UTC, MattiSG commented on README.md
> +You can learn more about [Open Terms Archive](https://github.com/ambanum/OpenTermsArchive) on the [dedicated repository](https://github.com/ambanum/OpenTermsArchive).
```suggestion
These service declarations are used by the [Open Terms Archive engine](https://github.com/ambanum/OpenTermsArchive).
```

2021-12-02 10:09 UTC, MattiSG approved these changes
👍

2021-12-02 10:09 UTC, MattiSG commented
Reminder to update the main branch in the settings once this PR is merged 🙂

2021-12-02 10:46 UTC, merged